version: '3'

services:
  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: $BD_DATABASE_NAME
    ports:
      - "3306:3306"
    volumes:
      - ./kubernetes/Global/v1.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      DB_HOST: 'mysql'
      DB_USER: $DB_USER
      BD_DATABASE_NAME: $BD_DATABASE_NAME

